osx_image: xcode8
language: objective-c
script:
  - xcodebuild test -project AssimpKit/OSX-Example/OSX-Example.xcodeproj -scheme AssimpSceneKit_LogicTests -destination 'platform=OS X,arch=x86_64'
  - xcodebuild test -project AssimpKit/iOS-Example/iOS-Example.xcodeproj -scheme AssimpSceneKit_LogicTests -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'