language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
  - echo Test the AssimpSceneKit static library for macOS
  - xctool -project AssimpKit/OSX-Example/OSX-Example.xcodeproj -scheme AssimpSceneKit_LogicTests -destination 'platform=OS X,arch=x86_64' clean test

  - echo Test the AssimpSceneKit static library for iOS
  - xctool -project AssimpKit/iOS-Example/iOS-Example.xcodeproj -scheme AssimpSceneKit_LogicTests -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6' clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)