language: objective-c
osx_image: xcode8

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

before_script:
    - git lfs pull

script:
  - echo Test the AssimpSceneKit static library for macOS
  - xcodebuild -project AssimpKit/Library/Library.xcodeproj -scheme AssimpKitTests_macOS -destination 'platform=OS X,arch=x86_64' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test

  - echo Test the AssimpSceneKit static library for iOS
  - xcodebuild -project AssimpKit/Library/Library.xcodeproj -scheme AssimpKitTests_iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)