language: objective-c
osx_image: xcode8
script:
  - xcodebuild \
      -project AssimpKit/OSX-Example/OSX-Example.xcodeproj \
      -scheme AssimpSceneKit_LogicTests \
      -destination 'platform=OS X,arch=x86_64'
      clean build test | xcpretty -c --test --color 
  - xcodebuild \
      -project AssimpKit/iOS-Example/iOS-Example.xcodeproj \
      -scheme AssimpSceneKit_LogicTests \
      -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' \
      clean build test | xcpretty -c --test --color 